CREATE TABLE MOOD (
ID NUMBER,
NOME_TAG VARCHAR2(20),
DESCRICAO VARCHAR2(50),

PRIMARY KEY(ID)
);

CREATE TABLE STATUS (
ID NUMBER,
NOME_TAG VARCHAR2(20),
DESCRICAO VARCHAR2(50),

PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
ID NUMBER,
USER_NAME VARCHAR2(20),
TIPO VARCHAR2(10),
NOME VARCHAR2(50),
EMAIL VARCHAR2(50),
SENHA VARCHAR2(10),
DICA_SENHA VARCHAR2(20),

ID_TAGMOOD NUMBER, 
ID_TAGSTATUS NUMBER,

PRIMARY KEY(ID,USER_NAME),
FOREIGN KEY (ID_TAGMOOD) REFERENCES MOOD (ID) ON DELETE CASCADE,
FOREIGN KEY (ID_TAGSTATUS) REFERENCES STATUS (ID) ON DELETE CASCADE

);

CREATE TABLE MUSICA(
ID NUMBER,
NOME VARCHAR2(20),
ARTISTA VARCHAR2(20),
PATH VARCHAR2(100),

PRIMARY KEY(ID)
);

CREATE TABLE CALCULA(
idcalcula INT,
idmusica INT,
tagmoodid INT, 
statustagid INT, 

FOREIGN KEY (idmusica) REFERENCES MUSICA (id) ON DELETE CASCADE,
FOREIGN KEY (tagmoodid) REFERENCES MOOD (id) ON DELETE CASCADE,
FOREIGN KEY (statustagid) REFERENCES STATUS (id) ON DELETE CASCADE,

PRIMARY KEY(idcalcula)

);

CREATE SEQUENCE SEQ_ID_USER INCREMENT BY 1 START WITH 1;



-- o script precisa ser alterado para incluir o UPDATE de USER em um condicional mood e status 