package view;

import controle.Cadastro;

public class TelaSignUp extends javax.swing.JFrame {

    /**
     * Creates new form TelaSignUp
     */
    public TelaSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        usernameCadastroTextField = new javax.swing.JTextField();
        premiumRadioButton = new javax.swing.JRadioButton();
        nomeCompletoTextField = new javax.swing.JTextField();
        freeRadioButton = new javax.swing.JRadioButton();
        emailCadastroTextField = new javax.swing.JTextField();
        passwordTipCadastroTextField = new javax.swing.JTextField();
        passwordCadastroLabel = new javax.swing.JLabel();
        nomeCompletoCadastroLabel = new javax.swing.JLabel();
        emailCadastroLabel = new javax.swing.JLabel();
        passwordTipCadastroLabel = new javax.swing.JLabel();
        passwordCadastroField = new javax.swing.JPasswordField();
        usernameCadastroLabel = new javax.swing.JLabel();
        passwordTipCadastroLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 255));
        setMinimumSize(new java.awt.Dimension(780, 520));
        setPreferredSize(new java.awt.Dimension(560, 360));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Usuário");

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("               ");

        cadastrarButton.setBackground(new java.awt.Color(255, 255, 204));
        cadastrarButton.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        cadastrarButton.setForeground(new java.awt.Color(51, 51, 51));
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setName("cadastrarButton"); // NOI18N
        cadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cadastrarButtonMouseReleased(evt);
            }
        });
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        premiumRadioButton.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        premiumRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        premiumRadioButton.setText("Premium User");
        premiumRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premiumRadioButtonMouseClicked(evt);
            }
        });

        freeRadioButton.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        freeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        freeRadioButton.setText("Free User");
        freeRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freeRadioButtonMouseClicked(evt);
            }
        });

        passwordCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        passwordCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordCadastroLabel.setText("Password:");

        nomeCompletoCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        nomeCompletoCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeCompletoCadastroLabel.setText("Nome Completo:");

        emailCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        emailCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailCadastroLabel.setText("Email:");

        passwordTipCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        passwordTipCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordTipCadastroLabel.setText("Password Tip:");

        usernameCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        usernameCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameCadastroLabel.setText("Username:");

        passwordTipCadastroLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        passwordTipCadastroLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordTipCadastroLabel1.setText("Tipo de Conta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCompletoCadastroLabel)
                    .addComponent(passwordCadastroLabel)
                    .addComponent(emailCadastroLabel)
                    .addComponent(usernameCadastroLabel)
                    .addComponent(passwordTipCadastroLabel)
                    .addComponent(passwordTipCadastroLabel1))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(premiumRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(freeRadioButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameCadastroTextField)
                        .addComponent(nomeCompletoTextField)
                        .addComponent(emailCadastroTextField)
                        .addComponent(passwordTipCadastroTextField)
                        .addComponent(passwordCadastroField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordCadastroField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCompletoCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTipCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTipCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumRadioButton)
                    .addComponent(freeRadioButton)
                    .addComponent(passwordTipCadastroLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButtonMouseReleased
        // TODO add your handling code here:
        
        //Variáveis que indicam atributos do usuário (tipo a ser definido)
        Cadastro cadastro;
        int id = 1;
        String username;
        String password;
        String nomeCompleto;
        String email;
        String passwordTip;
        int tipoDeUsuario = 0;
        
        //Variável para controle de erro no cadastro, valor para default
        String auxiliarRetornoDeCadastro;
        
        //Atribuindo valores da textBox para os atributos
        username = usernameCadastroTextField.getText();
        password = passwordCadastroField.getText();
        nomeCompleto = nomeCompletoTextField.getText();
        email = emailCadastroTextField.getText();
        passwordTip = passwordTipCadastroTextField.getText();
        
        //Instanciando cadastro
        cadastro = new Cadastro();

        //Verifica qual o tipo de conta especificado pelo usuário
        if (premiumRadioButton.isSelected() == true){
            tipoDeUsuario = 1;
        } else if (freeRadioButton.isSelected() == true){
            tipoDeUsuario = 2;
        } else {
            tipoDeUsuario = 0;
            jLabel3.setText("Digite um tipo de usuário!");
        }
        
        //Se o usuário tiver escolhido alguma opção para o tipo de conta, as instruções dentro do if irão verificar se as fields estão vazias
        if(tipoDeUsuario!=0){
            
            if("".equals(username) || "".equals(password) || "".equals(nomeCompleto) || "".equals(email) || "".equals(passwordTip)){
                jLabel3.setText("Por favor, preencha todos os campos!");
            }
            //Se não tiver nenhuma field vazia, o programa tentará cadastrar com os dados especificados
            else{
                //O retorno das operações irá para a variável auxiliarRetornoDeCadastro, para o tratamento de erros
                auxiliarRetornoDeCadastro = cadastro.receberInformacao(id, username, password, nomeCompleto, email, tipoDeUsuario, passwordTip);
                if("Sucesso".equals(auxiliarRetornoDeCadastro)){
                    jLabel3.setText("Cadastro do user "+username+" realizado com sucesso!");
                    usernameCadastroTextField.setText("");
                    passwordCadastroField.setText("");
                    nomeCompletoTextField.setText("");
                    emailCadastroTextField.setText("");
                    passwordTipCadastroTextField.setText("");
                }
                else if("Email ja cadastrado".equals(auxiliarRetornoDeCadastro)){
                    jLabel3.setText("Email "+email+" já está sendo usado, digite outro!");
                    emailCadastroTextField.setText("");
                }
                else if("Nome de Usuario ja cadastrado".equals(auxiliarRetornoDeCadastro)){
                    jLabel3.setText("Usuário "+username+" já está sendo usado, digite outro!");
                    usernameCadastroTextField.setText("");
                }
            }
        }
        
        //Se tiver retornado a 0, o cadastro foi feito com sucesso; se não, houve erro(s)
       // if("Sucesso".equals(auxiliarRetornoDeCadastro)){
       //     jLabel3.setText("Cadastro realizado com sucesso!");
         //   new TelaCadastroRealizado().setVisible(true);
        //}
        //else if(auxiliarRetornoDeCadastro==1){
         //   jLabel3.setText("Nome de usuário solicitado já foi cadastrado, favor digite outro!");
        //}
        //else if(auxiliarRetornoDeCadastro==2){
        //    jLabel3.setText("Email solicitado já foi cadastrado, favor digite outro!");
        //}

        
        
    }//GEN-LAST:event_cadastrarButtonMouseReleased

    private void premiumRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premiumRadioButtonMouseClicked
        // TODO add your handling code here:
        freeRadioButton.setSelected(false);
    }//GEN-LAST:event_premiumRadioButtonMouseClicked

    private void freeRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeRadioButtonMouseClicked
        // TODO add your handling code here:
         premiumRadioButton.setSelected(false);
    }//GEN-LAST:event_freeRadioButtonMouseClicked

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaSignUp().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel emailCadastroLabel;
    private javax.swing.JTextField emailCadastroTextField;
    private javax.swing.JRadioButton freeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomeCompletoCadastroLabel;
    private javax.swing.JTextField nomeCompletoTextField;
    private javax.swing.JPasswordField passwordCadastroField;
    private javax.swing.JLabel passwordCadastroLabel;
    private javax.swing.JLabel passwordTipCadastroLabel;
    private javax.swing.JLabel passwordTipCadastroLabel1;
    private javax.swing.JTextField passwordTipCadastroTextField;
    private javax.swing.JRadioButton premiumRadioButton;
    private javax.swing.JLabel usernameCadastroLabel;
    private javax.swing.JTextField usernameCadastroTextField;
    // End of variables declaration//GEN-END:variables
}
