package view;

import controller.ControleCadastro;

public class TelaSignUp extends javax.swing.JFrame {
    
    ControleCadastro controleCadastro = new ControleCadastro();
    /**
     * Creates new form TelaSignUp
     */
    public TelaSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelRetorno = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        usernameCadastroTextField = new javax.swing.JTextField();
        premiumRadioButton = new javax.swing.JRadioButton();
        nomeCompletoTextField = new javax.swing.JTextField();
        freeRadioButton = new javax.swing.JRadioButton();
        emailCadastroTextField = new javax.swing.JTextField();
        passwordTipCadastroTextField = new javax.swing.JTextField();
        passwordCadastroLabel = new javax.swing.JLabel();
        nomeCompletoCadastroLabel = new javax.swing.JLabel();
        emailCadastroLabel = new javax.swing.JLabel();
        passwordTipCadastroLabel = new javax.swing.JLabel();
        passwordCadastroField = new javax.swing.JPasswordField();
        usernameCadastroLabel = new javax.swing.JLabel();
        passwordTipCadastroLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadastrarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(780, 520));
        setPreferredSize(new java.awt.Dimension(560, 360));
        setSize(new java.awt.Dimension(700, 700));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Nanum Brush Script", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Usuário");

        labelRetorno.setForeground(new java.awt.Color(255, 51, 51));
        labelRetorno.setText("               ");

        cancelarButton.setBackground(new java.awt.Color(255, 255, 204));
        cancelarButton.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelarButton.setText("Cancelar");
        cancelarButton.setName("cancelarButton"); // NOI18N
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseReleased(evt);
            }
        });

        premiumRadioButton.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        premiumRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        premiumRadioButton.setText("Premium User");
        premiumRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premiumRadioButtonMouseClicked(evt);
            }
        });

        freeRadioButton.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        freeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        freeRadioButton.setText("Free User");
        freeRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freeRadioButtonMouseClicked(evt);
            }
        });

        passwordCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        passwordCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordCadastroLabel.setText("Password:");

        nomeCompletoCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        nomeCompletoCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeCompletoCadastroLabel.setText("Nome Completo:");

        emailCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        emailCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailCadastroLabel.setText("Email:");

        passwordTipCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        passwordTipCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordTipCadastroLabel.setText("Password Tip:");

        usernameCadastroLabel.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        usernameCadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameCadastroLabel.setText("Username:");

        passwordTipCadastroLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        passwordTipCadastroLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordTipCadastroLabel1.setText("Tipo de Conta:");

        jLabel2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://raw.githubusercontent.com/iagorichard/Soundmood/master/SoundMood/src/includes/soundmood%20.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        cadastrarButton1.setBackground(new java.awt.Color(255, 255, 204));
        cadastrarButton1.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        cadastrarButton1.setForeground(new java.awt.Color(51, 51, 51));
        cadastrarButton1.setText("Cadastrar");
        cadastrarButton1.setName("cadastrarButton"); // NOI18N
        cadastrarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cadastrarButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(labelRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCompletoCadastroLabel)
                                    .addComponent(passwordCadastroLabel)
                                    .addComponent(emailCadastroLabel)
                                    .addComponent(usernameCadastroLabel)
                                    .addComponent(passwordTipCadastroLabel)
                                    .addComponent(passwordTipCadastroLabel1))
                                .addGap(66, 66, 66)
                                .addComponent(premiumRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(freeRadioButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameCadastroTextField)
                                    .addComponent(nomeCompletoTextField)
                                    .addComponent(emailCadastroTextField)
                                    .addComponent(passwordTipCadastroTextField)
                                    .addComponent(passwordCadastroField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(cadastrarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addGap(45, 45, 45)
                .addComponent(labelRetorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordCadastroField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCompletoCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTipCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTipCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumRadioButton)
                    .addComponent(freeRadioButton)
                    .addComponent(passwordTipCadastroLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(cadastrarButton1))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Quando clicar no botão cadastrar, todas as ações dentro
     * do método cadastrarButtonMouseReleased serão realizadas, ou seja,
     * o sistema irá tentar cadastrar um novo usuário.
     * @param evt 
     */
    private void cancelarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseReleased
        // TODO add your handling code here:
        
        //Variáveis que indicam atributos do usuário (tipo a ser definido)
        
        this.setVisible(false);
        PrimeiraTela primeiraTela = new PrimeiraTela();
        
        primeiraTela.setVisible(true);
        
        //this.setVisible(false);
        
        
    }//GEN-LAST:event_cancelarButtonMouseReleased

    private void premiumRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premiumRadioButtonMouseClicked
        // TODO add your handling code here:
        freeRadioButton.setSelected(false);
    }//GEN-LAST:event_premiumRadioButtonMouseClicked

    private void freeRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeRadioButtonMouseClicked
        // TODO add your handling code here:
         premiumRadioButton.setSelected(false);
    }//GEN-LAST:event_freeRadioButtonMouseClicked

    private void cadastrarButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButton1MouseReleased
        // TODO add your handling code here:
        String retorno = controleCadastro.receberInformacao(usernameCadastroTextField.getText(), emailCadastroTextField.getText());
       
        String textBoxRetorno;
        boolean retornoGravar;
        
        if("email".equals(retorno)){
            textBoxRetorno = "Email existente!";
            labelRetorno.setText(textBoxRetorno);
        }else if("usuario".equals(retorno)){
           textBoxRetorno = "Usuario ja existente!";
           labelRetorno.setText(textBoxRetorno);
        }else{
            textBoxRetorno = "";
            labelRetorno.setText(textBoxRetorno);
            
            
            retornoGravar = controleCadastro.gravarInformacao(usernameCadastroTextField.getText(), passwordCadastroField.getText(), nomeCompletoTextField.getText(), emailCadastroTextField.getText(), 1, passwordTipCadastroTextField.getText());
            if(retornoGravar == true){
                this.setVisible(false);
                TelaSignIn telaSignIn = new TelaSignIn();
        
                telaSignIn.setVisible(true);
                
            }
        }
    }//GEN-LAST:event_cadastrarButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaSignUp().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton1;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel emailCadastroLabel;
    private javax.swing.JTextField emailCadastroTextField;
    private javax.swing.JRadioButton freeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelRetorno;
    private javax.swing.JLabel nomeCompletoCadastroLabel;
    private javax.swing.JTextField nomeCompletoTextField;
    private javax.swing.JPasswordField passwordCadastroField;
    private javax.swing.JLabel passwordCadastroLabel;
    private javax.swing.JLabel passwordTipCadastroLabel;
    private javax.swing.JLabel passwordTipCadastroLabel1;
    private javax.swing.JTextField passwordTipCadastroTextField;
    private javax.swing.JRadioButton premiumRadioButton;
    private javax.swing.JLabel usernameCadastroLabel;
    private javax.swing.JTextField usernameCadastroTextField;
    // End of variables declaration//GEN-END:variables
}
