/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.Cadastro;

/**
 *
 * @author biancamoreira
 */
public class TelaSignUp extends javax.swing.JFrame {

    /**
     * Creates new form TelaSignUp
     */
    public TelaSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameCadastroLabel = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        usernameCadastroTextField = new javax.swing.JTextField();
        nomeCompletoField = new javax.swing.JTextField();
        emailCadastroTextField = new javax.swing.JTextField();
        passwordTipCadastroField = new javax.swing.JTextField();
        passwordCadastroLabel = new javax.swing.JLabel();
        nomeCompletoCadastroLabel = new javax.swing.JLabel();
        emailCadastroLabel = new javax.swing.JLabel();
        passwordTipCadastroLabel = new javax.swing.JLabel();
        passwordCadastroField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        passwordTipCadastroLabel1 = new javax.swing.JLabel();
        premiumRadioButton = new javax.swing.JRadioButton();
        freeRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(560, 360));

        jLabel1.setText("Cadastro de Usuário");

        usernameCadastroLabel.setText("Username:");

        cadastrarButton.setBackground(new java.awt.Color(0, 0, 0));
        cadastrarButton.setForeground(new java.awt.Color(255, 255, 204));
        cadastrarButton.setIcon(new javax.swing.ImageIcon("/Users/biancamoreira/Documents/Universidade/UPE/Quinto Período/POO/buttons/button2.gif")); // NOI18N
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setName("cadastrarButton"); // NOI18N
        cadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cadastrarButtonMouseReleased(evt);
            }
        });

        passwordCadastroLabel.setText("Password:");

        nomeCompletoCadastroLabel.setText("Nome Completo:");

        emailCadastroLabel.setText("Email:");

        passwordTipCadastroLabel.setText("Password Tip:");

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("               ");

        passwordTipCadastroLabel1.setText("Tipo de Conta:");

        premiumRadioButton.setText("Premium User");
        premiumRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premiumRadioButtonMouseClicked(evt);
            }
        });

        freeRadioButton.setText("Free User");
        freeRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freeRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCompletoCadastroLabel)
                    .addComponent(passwordCadastroLabel)
                    .addComponent(emailCadastroLabel)
                    .addComponent(usernameCadastroLabel)
                    .addComponent(passwordTipCadastroLabel)
                    .addComponent(passwordTipCadastroLabel1))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(premiumRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(freeRadioButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameCadastroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(nomeCompletoField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(emailCadastroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(passwordTipCadastroField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(passwordCadastroField)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordCadastroField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCompletoCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTipCadastroField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTipCadastroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumRadioButton)
                    .addComponent(freeRadioButton)
                    .addComponent(passwordTipCadastroLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(cadastrarButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButtonMouseReleased
        // TODO add your handling code here:
        //Pega informacao do cliente a partir das textboxes
        Cadastro cadastro;
        String username;
        String password;
        String nomeCompleto;
        String email;
        int tipoDeUsuario;
        int auxiliarRetornoDeCadastro;
        
        
        //designa variaveis para elas
        username = usernameCadastroTextField.getText();
        password = passwordCadastroField.getText();
        nomeCompleto = nomeCompletoField.getText();
        email = emailCadastroTextField.getText();
        //consertar isso do selected
        //if (premiumRadioButton.selected() == true){
        //    tipoDeUsuario = 1;
        //}else if(freeRadioButton.selected() == true){
       //     tipoDeUsuario = 0; 
       // }else{
            //muda na label - coloca mensagem 'selecione um tipo de usuario'
        //}
        
        //criar construtor e jogar dados
        cadastro = new Cadastro();
        
        
         //cadastro.receberInformacao(username, password, nomeCompleto, email, tipo);
        
        //coloca dentro do controle de cadastro 
        // testar email - com @ 
        // testar se ja existe email e username e retornar algum valor se existir
        
        
        //dependendo do retorno, a label acima dos textboxes retornara um valor e apagara
        //o que esta escrito dentro da textbox
        //if auxiliarRetornoDeCadastro == 1 
        //email ja existente - jlabel3
        //zera a textbox email
        //zera valor de variavel responsavel pela textbox email
        
        //else if auxiliarRetornoDeCadastro == 2
        //usuario ja existente - jalabel3
        //zera textbox usuario
        //zera valor de variavel responsavel pela textbox usuario
        
        //else if auxiliarRetornoDeCadastro == 0
        //cadastro realizado com sucesso e chama uma tela de retorno
        //new TelaCadastroRealizado().setVisible(true);
       

        // TelaSignUp.setVisible(true);
        //Manda pra a tela de cadastro realizado
       
       
       
        
        
    }//GEN-LAST:event_cadastrarButtonMouseReleased

    private void premiumRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premiumRadioButtonMouseClicked
        // TODO add your handling code here:
        freeRadioButton.setSelected(false);
    }//GEN-LAST:event_premiumRadioButtonMouseClicked

    private void freeRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeRadioButtonMouseClicked
        // TODO add your handling code here:
         premiumRadioButton.setSelected(false);
    }//GEN-LAST:event_freeRadioButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSignUp().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel emailCadastroLabel;
    private javax.swing.JTextField emailCadastroTextField;
    private javax.swing.JRadioButton freeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nomeCompletoCadastroLabel;
    private javax.swing.JTextField nomeCompletoField;
    private javax.swing.JPasswordField passwordCadastroField;
    private javax.swing.JLabel passwordCadastroLabel;
    private javax.swing.JTextField passwordTipCadastroField;
    private javax.swing.JLabel passwordTipCadastroLabel;
    private javax.swing.JLabel passwordTipCadastroLabel1;
    private javax.swing.JRadioButton premiumRadioButton;
    private javax.swing.JLabel usernameCadastroLabel;
    private javax.swing.JTextField usernameCadastroTextField;
    // End of variables declaration//GEN-END:variables
}
